import esbuild from "esbuild";
import process from "node:process";
import builtins from "builtin-modules";
import { sassPlugin } from "esbuild-sass-plugin";

const prod = process.argv[2] === "production";

const sass = sassPlugin(
	/** @type { import("esbuild-sass-plugin").Options } */
	{}
);
const context = await esbuild.context({
	banner: {
		js: getBanner(),
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [
		sassPlugin(
			/** @type { import("esbuild-sass-plugin").} */
			{
				filter: "styles/*.scss",
			}
		),
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}

function getBanner() {
	return;
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
		`;
}
