name: Parser - Publish

on:
    push:
        tags:
            - "*"

        paths:
            - "packages/canva-parser"
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"

            - name: Build plugin
              run: |
                  npm install --workspace=@obsidian-canva-embed/canva-parser
                  npm run build --workspace=@obsidian-canva-embed/canva-parser

            - name: Publish package
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  echo "Publishing package"
                  npm publish --workspace=@obsidian-canva-embed/canva-parser
