name: Parser - Publish

on:
    push:
        branches:
            - master

        paths:
            - "packages/parser/**"
            - .github/workflows/parser.publish.yml
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"

            - name: Build plugin
              run: |
                  npm run parser -- install
                  npm run parser -- run build

            - name: Publish package
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  echo "Publishing package"
                  npm run parser -- publish
