name: Plugin - Release

on:
    push:
        branches:
            - master

        paths:
            - "packages/plugin/**"
            - manifest.json
            - README.md
            - LICENSE.md
            - versions.json
            - .github/workflows/plugin.release.yml

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"

            - name: Build plugin
              run: |
                  npm run plugin -- install
                  npm run plugin -- run build
            - name: Tag and release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  set -ex
                  version="$(npm run plugin -- run get-version)"
                  echo "Version: $version"
                  git tag -a "$version" -m "$version"
                  git push origin "$version"
                  gh release create "$version" \
                    --title="$version" \
                    packages/plugin/dist/{main.js,styles.css} \
                    manifest.json versions.json
