name: Plugin - Release

on:
    push:
        branches:
            - master

        paths:
            - "packages/plugin/**"
            - manifest.json
            - README.md
            - LICENSE.md
            - versions.json
            - .github/workflows/plugin.release.yml

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"

            - name: Build plugin
              run: |
                  npm run parser -- install
                  npm run parser -- run build
                  npm run plugin -- install
                  npm run plugin -- run build
            - name: Get version string
              id: version
              run: |
                  cd packages/plugin
                  echo "result=$(node tools/get-version.cjs)" >> "$GITHUB_OUTPUT"
                  cd ../..
            - name: Push tag
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                set -ex
                tag="${{ steps.version.outputs.result }}"
                message="${{ steps.version.outputs.result }}"

                git config user.name "${GITHUB_ACTOR}"
                git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

                git tag -a "${tag}" -m "${message}"
                git push origin "${tag}"
            - name: Tag and release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  set -ex
                  version="${{ steps.version.outputs.result }}"
                  echo "Version: $version"
                  gh release create "$version" \
                    --title="$version" \
                    packages/plugin/dist/{main.js,styles.css} \
                    manifest.json versions.json
